### ISSUE TITLE
Add support for npm3 or dedupe

### ISSUE THREAD

**Issue by Frizi** [localnerve/html-snapshots#41]
Right now phantomjs bin path is hardcoded here
https://github.com/localnerve/html-snapshots/blob/master/lib/html-snapshots.js#L23

When `html-snapshots` is installed with npm3 (or dedupe was used), phantom is installed in different location. In my case this path would work `'../../.bin/phantomjs'`, but you cannot assume that really.

You may try your luck with this code from `karma-phantomjs-launcher`:

```javascript
var phantomJSExePath = function () {
  // If the path we're given by phantomjs is to a .cmd, it is pointing to a global copy. 
  // Using the cmd as the process to execute causes problems cleaning up the processes 
  // so we walk from the cmd to the phantomjs.exe and use that instead.

  var phantomSource = require('phantomjs').path;

  if (path.extname(phantomSource).toLowerCase() === '.cmd') {
    return path.join(path.dirname( phantomSource ), '//node_modules//phantomjs//lib//phantom//phantomjs.exe');
  }

  return phantomSource;
};
```

**Comment by localnerve** [comment]
This has always been an issue - well before npm3.
The hard-coded path you reference is just a default.

The default bin path can be overriden with the phantomjs option, found at the bottom of [this section in the readme](https://github.com/localnerve/html-snapshots#process-control-options).
So, the phantomjs supplied with this lib is entirely optional.

I'm assuming you are suggesting that there should be a different default phantomjs location. I've a couple of questions on that implied suggestion:
1. What phantomjs location & version are you actively referencing that prompted this issue (presume via this lib pkg json)?
I ask this because last year we found a package driven [MacOSX difference](https://github.com/localnerve/html-snapshots/issues/17) that invalidated referencing phantomjs/lib/phantom/phantomjs.exe directly (perms on file not executable after install). Maybe this has changed again and would be good to know which version to get to test a next change. 
Also, could be that you are getting a different phantomjs in your particular project dep situation.
2. Is npm3 changing [files/folders](https://docs.npmjs.com/files/folders)?
3. Is the package referenced in karma-phantomjs-launcher using the same phantomjs package referenced by this lib?

Thanks in advance for any additional feedback you can supply.

**Comment by Frizi** [comment]
1. paths to all 3 modules:
* `node_modules/html-snapshots`, v0.8.1, dependency on phantomjs ^1.9.16
* `node_modules/karma-phantomjs-launcher`, v0.1.4, dependency on phantomjs ~1.9
* `node_modules/phantomjs`, v1.9.17

2. packages are now installed as flat as possible, per-package node_modules folder is only created when there is a version conflict.
https://github.com/npm/npm/releases/tag/v3.0.0 check section "Flat, flat, flat!"

3. Yes, at least this lib should use it, but doesn't properly.

Simple `require('phantomjs')` will always refer to the correct path, so it should be a preferred solution to find a module.

**Comment by localnerve** [comment]
Let's be more specific on what you are saying the change should be (So I'm certain I understand). Here's my attempt:

> Update the [default phantomjs path value](https://github.com/localnerve/html-snapshots/blob/566639f1e932e0032e95dcd68b0270e67c51f2c6/lib/html-snapshots.js#L23) used by this package to be dependent on the path property exported from the [phantomjs npm package](https://github.com/Medium/phantomjs). The default value will now come from [this code](https://github.com/Medium/phantomjs/blob/a1efb07eebdf264d43f48ae644e41a7e7c01f691/lib/phantomjs.js#L18) in the phantomjs package.

> Using this property should always be the correct path for all npm versions, and will serve well in the npm3, dedupe case.

Easy enough, please confirm I got it right.
Thanks!

**Comment by Frizi** [comment]
Yes, you got it right. The code I posted at the top is actually working well in all these cases. Just remember to allow the user to alter this path anyway.

**Comment by localnerve** [comment]
OK, I have a release candidate that runs correctly on Linux. It also makes successful substitutions via the phantomjs option (this is how I run on Travis-CI).

I noticed that this technique (you posted from above, the essence of the change) is only used by karma-phantomjs-launcher for [win32](https://github.com/karma-runner/karma-phantomjs-launcher/blob/ef6612be1f88e975d43d94c85ef045559363cc54/index.js#L99).
I'm using it for every/any platform. Works for Linux.

Can you please [review](c2f5e2830fcb16a6e08c45175357df70698cc9b1) the change and test your use case?

To test, drop the RC in your package.json via `git://github.com/localnerve/html-snapshots#rc-0.10.0` ?

**Comment by localnerve** [comment]
I've confirmed working on mac, you have any feedback in your case?
