### ISSUE TITLE
What is the expectation of the snapshot rendering?no css there are no images

### ISSUE THREAD

**Issue by yellownoggin** [localnerve/html-snapshots#45]
1. First, regarding your blog post
http://www.localnerve.com/blog/how-are-you-using-html-snapshots/

I know this is might be and old question, and tools and scenarios have changed slightly,  but just in case you didn't get a definitive answer to your question. I wrapped html-snapshot in a gulp task.

2.The rendering of the snapshot pages by the google crawler. Is the intention not to worry about the css or images or possible layout issues. For example, links and the main content  are overlapping each other. Is that something we should be concerned about?

3. site maps: do use pretty urls or hashbangs?

thanks for the module, worked as advertised : -)

**Comment by localnerve** [comment]
That's a good question, and thanks for the info.
However, all this ajax crawling concern stuff appears [deprecated](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) now.

To answer you: Yes - It is definitely possible that layout has an impact to the crawler, if it results in the hiding of something important to Google/Crawler. Also, certain types of missing images could also be impactful if they contain data that signals the crawler (exif, etc).

In the past, I had avoided this by waiting on the last (time-wise) relevant classes to show up. Ideally, this doesn't require any special code just for snapshotting - Depends on the app.

Nowadays I use server-side render with universal apps like [this] (https://github.com/localnerve/react-pwa-reference) - Universal ~~isomorphic~~ apps render both on client and server. FWIW there are [relatively maintained projects](https://github.com/localnerve/flux-react-example) that show my evolution into that design in case it helps - There are also some great examples at Yahoo. Performance/mobile concerns forced me into that design, and I also find it very much simpler to manage and think about (than client-side only apps).

**But** when I was doing client-side SPAs with html-snapshots, I always used pretty urls in the sitemaps.
Each page would contain `<meta name="fragment" content="!">`, and I would have a rule (usually .htaccess or express middleware) to serve the generated snapshots for escaped fragment requests.

It used to be that you could test this out in Google Webmaster Tools by using the Fetch facility to get the _escaped_fragment_ URL of a page. The result is what the crawler will see, and this always turned out to be true in the SERPs.

Again, I'm not sure any of this ajax crawling stuff is useful or valid anymore since 10/2015 and YMMV.
Hope this is helpful.

**Comment by henns20** [comment]
Thanks. A little behind on the seo side of things as it pertains to javascript frameworks. I thought that even with the new specifications that you should have a convention that it degrades gracefully with google & for it was still a factor with search engines like Bing.

But came across this [link](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) seems to tell me not to do snapshots anymore or at least I'll be old convention allowed.

>  If you pre-render pages, make sure that the content served to Googlebot matches the user's experience, both how it looks and how it interacts. Serving Googlebot different content than a normal user would see is considered cloaking, and would be against our Webmaster Guidelines.

**One last question,** I understand you don't use the snapshots/escaped fragment convention, but does that also mean that you do not use the `<meta name="fragment" content="!">` since you are doing server-side rendering?

By the way, impressed by the projects you have done(creation/writing). Super clean with good docs.

**Comment by localnerve** [comment]
Thanks for the compliments!

I saw the cloaking warning too, and that's actually an older warning as well - but it's worth obeying.
However, if you continue snapshotting, you should wait longer for the page to be rendered so you will get a more complete layout - but you probably won't ever get images (unless you write code specifically for that). I personally would not worry about that difference in cloaking terms - I've never been punished for snapshots with partial or incomplete images - but if you are still concerned I'd ask a Google Group about this.

I don't use `<meta name="fragment" content="!">` in my html anymore because this is an instruction to the crawler to callback with an `_escaped_fragment_` request for indexing. This (and the rewrite rule/middleware to serve the snapshots) is what keeps your urls clean.

But, since I don't want that behavior anymore, I don't include it.

In fact, [here](https://github.com/localnerve/react-pwa-reference/blob/master/src/application/components/Html.jsx) is a close representation of the concerns covered in my html these days, and [here](http://www.webpagetest.org/results.php?test=160516_97_RDM) is the result over a 3G network with SSL, multiple asset hosts, and a free-tier app host.

**Comment by yellownoggin** [comment]
thanks for you responses, help, and links. Meant to get back sooner to close. cheers.
